import { Movie } from './movie.model';
import { ReviewService } from '../review.service';

export class MovieService{
    private reviewService = new ReviewService;
    private movies : Movie [] = [
        {
            title: 'Skyward Bound',
            description: 'An adventurous journey across the skies in a steampunk world.',
            genre: 'Adventure',
            duration: 125,
            director: 'Aria Wren',
            actors: ['Leo Cross', 'Mina Vale', 'Oscar Trent'],
            releaseDate: new Date('2024-05-01'),
            screeningDate: new Date('2025-05-10'),
            screeningTimes: new Map([
              [new Date('2025-05-10T14:00:00'), 40],
              [new Date('2025-05-10T19:00:00'), 40],
            ]),
            ticketPrice: 12.99,
            rating: this.reviewService.getAverageRatingByTitle("Skyward Bound"),
            imageUrl: 'https://cdn.pixabay.com/photo/2021/12/24/12/13/fantasy-6891021_640.jpg',
          },
          {
            title: 'Skyward Bound',
            description: 'An adventurous journey across the skies in a steampunk world.',
            genre: 'Adventure',
            duration: 125,
            director: 'Aria Wren',
            actors: ['Leo Cross', 'Mina Vale', 'Oscar Trent'],
            releaseDate: new Date('2024-05-01'),
            screeningDate: new Date('2025-05-11'),
            screeningTimes: new Map([
              [new Date('2025-05-11T16:00:00'), 45],
              [new Date('2025-05-11T20:00:00'), 30],
            ]),
            ticketPrice: 12.99,
            status: null,
            rating: this.reviewService.getAverageRatingByTitle("Skyward Bound"),
            imageUrl: 'https://cdn.pixabay.com/photo/2021/12/24/12/13/fantasy-6891021_640.jpg',
          },
          {
            title: 'Shadows of Yesterday',
            description: 'A heart-wrenching drama about lost time and redemption.',
            genre: 'Drama',
            duration: 142,
            director: 'Miles Carter',
            actors: ['Eleanor Swift', 'Damian Holt'],
            releaseDate: new Date('2023-10-15'),
            screeningDate: new Date('2025-05-12'),
            screeningTimes: new Map([
              [new Date('2025-05-12T16:00:00'), 0],
              [new Date('2025-05-12T20:00:00'), 20],
            ]),
            ticketPrice: 11.5,
            rating: this.reviewService.getAverageRatingByTitle("Shadows of Yesterday"),
            imageUrl: 'https://cdn.pixabay.com/photo/2016/06/28/19/38/time-1485384_640.jpg',
          },
          {
            title: 'Circuit Breaker',
            description: 'A high-stakes cyber-thriller about hackers saving the world.',
            genre: 'Thriller',
            duration: 108,
            director: 'Nina Torres',
            actors: ['Kai Monroe', 'Isla Gray'],
            releaseDate: new Date('2024-03-22'),
            screeningDate: new Date('2025-05-13'),
            screeningTimes: new Map([
              [new Date('2025-05-13T18:00:00'), 35],
            ]),
            ticketPrice: 13.25,
            rating: this.reviewService.getAverageRatingByTitle("Circuit Breaker"),
            imageUrl: 'https://cdn.pixabay.com/photo/2022/09/28/02/50/matrix-7484076_640.jpg',
          },
          {
            title: 'Whiskered Warriors',
            description: 'Animated feline heroes embark on a hilarious quest.',
            genre: 'Animation',
            duration: 95,
            director: 'Poppy Lane',
            actors: ['Voice of Tom Hart', 'Voice of Lila Moon'],
            releaseDate: new Date('2024-11-01'),
            screeningDate: new Date('2025-05-14'),
            screeningTimes: new Map([
              [new Date('2025-05-14T12:00:00'), 60],
              [new Date('2025-05-14T15:00:00'), 0],
            ]),
            ticketPrice: 10.0,
            rating: this.reviewService.getAverageRatingByTitle("Whiskered Warriors"),
            imageUrl: 'https://cdn.pixabay.com/photo/2024/10/21/02/31/ai-generated-9136058_640.png',
          },
          {
            title: 'Neon Wasteland',
            description: 'In a dystopian future, a rogue detective fights corruption.',
            genre: 'Sci-Fi',
            duration: 130,
            director: 'Dex Vega',
            actors: ['Nova Reyes', 'Jett Orion'],
            releaseDate: new Date('2023-07-04'),
            screeningDate: new Date('2025-05-15'),
            screeningTimes: new Map([
              [new Date('2025-05-15T21:00:00'), 25],
            ]),
            ticketPrice: 14.75,
            rating: this.reviewService.getAverageRatingByTitle("Neon Wasteland"),
            imageUrl: 'https://cdn.pixabay.com/photo/2019/07/01/14/18/fantasy-4310034_640.jpg',
          },
          {
            title: 'Neon Wasteland',
            description: 'In a dystopian future, a rogue detective fights corruption.',
            genre: 'Sci-Fi',
            duration: 130,
            director: 'Dex Vega',
            actors: ['Nova Reyes', 'Jett Orion'],
            releaseDate: new Date('2023-07-04'),
            screeningDate: new Date('2025-05-16'),
            screeningTimes: new Map([
              [new Date('2025-05-16T23:00:00'), 20],
            ]),
            ticketPrice: 14.75,
            rating: this.reviewService.getAverageRatingByTitle("Neon Wasteland"),
            imageUrl: 'https://cdn.pixabay.com/photo/2019/07/01/14/18/fantasy-4310034_640.jpg',
          },
          {
            title: 'Haunting Echoes',
            description: 'A chilling ghost story that tests the limits of fear.',
            genre: 'Horror',
            duration: 100,
            director: 'Rhea Cross',
            actors: ['Seth Drake', 'Clara Bloom'],
            releaseDate: new Date('2024-09-30'),
            screeningDate: new Date('2025-05-16'),
            screeningTimes: new Map([
              [new Date('2025-05-16T22:30:00'), 20],
            ]),
            ticketPrice: 12.0,
            rating: this.reviewService.getAverageRatingByTitle("Haunting Echoes"),
            imageUrl: 'https://cdn.pixabay.com/photo/2020/06/05/19/02/chamber-5264172_640.jpg',
          },
          {
            title: 'Velvet Strings',
            description: 'An inspiring musical journey of a violin prodigy.',
            genre: 'Musical',
            duration: 115,
            director: 'Theo Silver',
            actors: ['Amira Wells', 'Jonas Cliff'],
            releaseDate: new Date('2023-12-20'),
            screeningDate: new Date('2025-05-17'),
            screeningTimes: new Map([
              [new Date('2025-05-17T17:00:00'), 45],
            ]),
            ticketPrice: 13.5,
            status: 'watched',
            rating: this.reviewService.getAverageRatingByTitle("Velvet Strings"),
            imageUrl: 'https://cdn.pixabay.com/photo/2024/05/02/07/11/woman-8733934_640.jpg',
          },
          {
            title: 'Cursed Sands',
            description: 'Archaeologists uncover a deadly ancient secret in Egypt.',
            genre: 'Adventure',
            duration: 110,
            director: 'Lana Crosswell',
            actors: ['Ezra King', 'Zara Night'],
            releaseDate: new Date('2024-02-10'),
            screeningDate: new Date('2025-05-18'),
            screeningTimes: new Map([
              [new Date('2025-05-18T14:30:00'), 40],
            ]),
            ticketPrice: 11.75,
            rating: this.reviewService.getAverageRatingByTitle("Cursed Sands"),
            imageUrl: 'https://cdn.pixabay.com/photo/2017/06/21/20/20/mysticism-2428432_640.jpg',
          },
          {
            title: 'Breaking the Ice',
            description: 'A sports comedy about an underdog curling team.',
            genre: 'Comedy',
            duration: 102,
            director: 'Harvey Stone',
            actors: ['Maya Sparks', 'Nick Wilder'],
            releaseDate: new Date('2024-01-05'),
            screeningDate: new Date('2025-05-19'),
            screeningTimes: new Map([
              [new Date('2025-05-19T13:00:00'), 50],
              [new Date('2025-05-19T18:00:00'), 30],
            ]),
            ticketPrice: 10.5,
            rating: this.reviewService.getAverageRatingByTitle("Breaking the Ice"),
            imageUrl: 'https://cdn.pixabay.com/photo/2015/05/16/09/17/curling-769673_640.jpg',
          },
          {
            title: 'Kingdoms Rise',
            description: 'An epic fantasy tale of war, loyalty, and magic.',
            genre: 'Fantasy',
            duration: 155,
            director: 'Ember Knight',
            actors: ['Rowan Vance', 'Lyra Wren'],
            releaseDate: new Date('2024-08-12'),
            screeningDate: new Date('2025-05-20'),
            screeningTimes: new Map([
              [new Date('2025-05-20T15:00:00'), 40],
              [new Date('2025-05-20T20:00:00'), 35],
            ]),
            ticketPrice: 15.99,
            rating: this.reviewService.getAverageRatingByTitle("Kingdoms Rise"),
            imageUrl: 'https://cdn.pixabay.com/photo/2024/06/13/08/19/knight-8827001_960_720.jpg',
          },
          {
            title: 'Kingdoms Rise',
            description: 'An epic fantasy tale of war, loyalty, and magic.',
            genre: 'Fantasy',
            duration: 155,
            director: 'Ember Knight',
            actors: ['Rowan Vance', 'Lyra Wren'],
            releaseDate: new Date('2024-08-12'),
            screeningDate: new Date('2025-05-21'),
            screeningTimes: new Map([
              [new Date('2025-05-21T14:00:00'), 50],
              [new Date('2025-05-21T19:30:00'), 40],
            ]),
            ticketPrice: 15.99,
            rating: this.reviewService.getAverageRatingByTitle("Kingdoms Rise"),
            imageUrl: 'https://cdn.pixabay.com/photo/2024/06/13/08/19/knight-8827001_960_720.jpg',
          },
    ];

    getMovies() {
        return this.movies;
    }

    getMovieByTitle(title: string): Movie {
      var movie : Movie = this.movies.filter(movie => movie.title === title)[0];
      return movie;
    }

}